version: '2'
services:
  php:
    image: webgriffe/php-apache-base
    container_name: project
    volumes_from:
      - unison
    links:
      - mariadb
    volumes:
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    ports:
      - "80:80"
    environment:
      - APACHE_DOC_ROOT=/var/www/html
      - DB_HOST=project-sql
    working_dir: /var/www/html

  unison:
    image: leighmcculloch/unison
    container_name: project-unison
    environment:
      - UNISON_VERSION=2.48.3
      - UNISON_WORKING_DIR=/var/www/html
    volumes:
      - /var/www/html
    ports:
      - "5000:5000"

  mariadb-data:
    image: tianon/true
    volumes:
      - ./mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.1.10
    container_name: project-sql
    ports:
      - "3306:3306"
    volumes_from:
      - "mariadb-data"
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_DATABASE=project